### ISSUE TITLE
easy way to see the tracks?

### ISSUE THREAD

**Issue by EdwardHuCS** [craffel/pretty-midi#140]
Is there some way for me to access the list of tracks in a midi file? I see there is an `instruments` attribute in PrettyMIDI but what if I want to access a track by index?

**Comment by craffel** [comment]
No, there is no 1:1 analogy between an object in pretty_midi and a MIDI track.  MIDI tracks are a pretty useless concept (conceptually) because they can contain an arbitrary number of different instruments over the course of the track.  Each instrument (according to program changes) on each track on each channel gets turned into a separate Instrument by pretty_midi.  If you want low-level access to MIDI primitives, I'd suggest using mido directly.
