### ISSUE TITLE
Empty array dtype issue in latest numpy

### ISSUE THREAD

**Issue by mattmcvicar** [craffel/pretty-midi#58]
Due to this change in numpy 1.10:

https://github.com/numpy/numpy/blob/master/doc/release/1.10.0-notes.rst#default-casting-rule-change

empty arrays are cast as type np.float64 and cannot be added to type np.int16, which is what all calls to get_piano_roll (both pretty_midi.py and instrument.py). This can be solved I think by forcing all arrays to explicitly be of type np.int16 (even the empty ones). MWE to reproduce the error:

`import jams
import pretty_midi
import numpy as np

print jams.__version__
print pretty_midi.__version__
print np.__version__

jam = jams.load('./jams/TRAAAZF12903CCCF6B.jams')
ann = jam.search(namespace='beat')[0]

midi_md5 = ann.annotation_metadata.annotator.midi_md5

midi_object = pretty_midi.PrettyMIDI(
    'mid_aligned/TRAAAZF12903CCCF6B/{}.mid'.format(midi_md5))

piano_roll = midi_object.get_piano_roll()`

**Comment by craffel** [comment]
After some thought, I don't really see any reason to have the piano roll matrices be `int16` dtype, because while it follows from velocities being integer, I can also see it creating issues downstream like this one or in user code.  It seems like this is a grandfathered-in convention from the [very days](https://github.com/craffel/pretty-midi/commit/be6193298e30541f5038b62d05591039920df1e3), so I can't remember exactly why I did it this way, but I also tend to not trust code I wrote more than a year ago.  So, I've removed all of the `int16` dtype specifications in the piano roll functions in 80ac6cd.  It works fine for me now with numpy 1.10.4, if everything is working for you too now can you close?  Thanks for reporting.

**Comment by mattmcvicar** [comment]
Yep, works for me on latest commit and numpy 1.10.4. Thanks.
