### ISSUE TITLE
Get "track" names for instruments

### ISSUE THREAD

**Issue by justinsalamon** [craffel/pretty-midi#59]
@craffel is it possible to obtain the MIDI "track" names for the `midi_data.instruments` ? 

I need to convert a set of MIDI files to JAMS files, but I only want to extract the notes of one "track" (or instrument) from each MIDI file, and I know the name of that track. I've been playing around with `pretty_midi` but haven't been able to get at this information. As an example, if I import one of these MIDI files into GarageBand I can see the track names: http://i.imgur.com/ziGf3I7.png

Is there a way to extract this information using `pretty_midi`?

**Comment by craffel** [comment]
`pretty_midi` discards the track name, because it collapses tracks into instruments by program number.  So, for example, in your GarageBand screenshot, tracks MELODY and SQ-R will be put into the same `pretty_midi.Instrument` because they have the same program number.  There are various reasons for this; I'd be happy to go into it if you want.

It should be possible to keep track of any `midi.TrackNameEvent`s while populating the instruments (the method `pretty_midi.PrettyMIDI._load_instruments`) and store them in the `Instruments`, maybe in a list or something.  I have not added this functionality, mainly because it is not directly compatible with `pretty_midi`'s representation of MIDI instruments, but moreso because in my experience relatively few MIDI files "in the wild" make use of track name events, and when they are used there's no standardization (unlike, say, program numbers thanks to general MIDI).

**Comment by justinsalamon** [comment]
Hmm, I see. This might be a problem for me then since I only want the notes from the MELODY track. I'll have a look at `pretty_midi.PrettyMIDI._load_instruments` and see if I can figure out how to implement what you suggest.  If I do, would this interest you as a PR, or would this forever be outside the scope of `pretty_midi`?

**Comment by craffel** [comment]
I'd suggest you just re-write the MIDI file with only the MELODY track (and, assuming your MIDI file is type 1, track 0 to retain timing information) in tact, using python-midi.
```Python
import midi
m = midi.read_midifile('your_file.mid')
m = [t for n, t in enumerate(m) if n == 0 or any(isinstance(e, midi.TrackNameEvent) and e.text == 'MELODY' for e in t)]
midi.write_midifile('your_file_melofy_only.mid')
```
(untested!)

Of course, if you want to try to include this information in a sane way in a PR, I'd welcome it, but I've avoided doing so because I can't think of a very sane way to do it.

**Comment by justinsalamon** [comment]
>Of course, if you want to try to include this information in a sane way in a PR, I'd welcome it, but I've avoided doing so because I can't think of a very sane way to do it.

Yeah I don't think I'll try that :)

But thanks for the suggestion of re-writing the MIDI file, got it to work with a couple of minor tweaks:
```python
import midi
m = midi.read_midifile('your_file.mid')
melody = [t for n, t in enumerate(m)
          if n == 0 or any(isinstance(e, midi.TrackNameEvent) 
                           and e.text == 'MELODY' for e in t)]
m = midi.Pattern(tracks=melody, resolution=m.resolution, 
                 format=m.format, tick_relative=m.tick_relative)
midi.write_midifile('your_file_melody_only.mid', m)
pm = pretty_midi.PrettyMIDI('your_file_melody_only.mid')
```
Guess we can close this then?

**Comment by craffel** [comment]
Haha yes, in retrospect I botched that write-call pretty badly :) Glad that worked!

**Comment by justinsalamon** [comment]
p.s - for the record, the code I pasted above seems to work for some files but not for others, in that once I save the melody-only midi file to disk, timidity can't play it for some reason. The curious (and lucky) thing is that if I load this file using `pretty_midi` it still produces a list of notes which (afaict) seems correct.

**Comment by craffel** [comment]
Hm, that is strange.  That's something I would try to make a minimal example for and report over at https://github.com/vishnubob/python-midi

**Comment by justinsalamon** [comment]
yes good idea, will do.

**Comment by justinsalamon** [comment]
Update: turns out some melody tracks have spaces in the text field, so the condition `e.text == 'MELODY'` wasn't catching them, consequently generating an empty midi file. Changing it to `'MELODY' in e.text` solves this issue.

I'm still getting some tracks that won't play in timidity, but I think now it's just a soundbank mapping issue (timidity says "No instrument mapped to tone bank 0, program 22 - this instrument will not be heard.
No pre-resampling cache hit"). They play fine in QuickTime.

**Comment by craffel** [comment]
In 0ca39fd1b1558468a402f1cf8fa126ce4ed7e76a I removed the behavior that `pretty_midi` collapses tracks into instruments by program number.  So, it is now possible to give each `Instrument` a track name (if one appears) according to the track the instrument appears on.  Of course, this is not guaranteed to be a unique name because different instruments can appear on a given track (via channels and program changes).  This would be particularly problematic in type-0 MIDI files, where all events occur on a single track (but on different channels) - in this case, all `Instrument`s would be given the same name (i.e., the name of the sole track, assuming a track name event appears on it).  I think a sane solution would be to only populate the `Instrument` names if there is more than 1 track.  I'll reopen this with the intention of doing this eventually.

**Comment by craffel** [comment]
Also relevant are instrument name and program name meta-events, as well as channel marker meta-events for type 0 MIDI files.

**Comment by justinsalamon** [comment]
> In 0ca39fd I removed the behavior that pretty_midi collapses tracks into instruments by program number

Ha, this change might actually break some of my existing code. Maybe support backwards compatibility via an optional arg?

**Comment by craffel** [comment]
> Ha, this change might actually break some of my existing code. Maybe support backwards compatibility via an optional arg?

There's really no way to have the old behavior without introducing blatantly wrong behavior (i.e. collapsing pitch bends and control changes onto one instrument), see the commit note.  You can always collapse instruments yourself by combining all attributes of instruments with the same program number and `is_drum`, which will work before or after this commit (before the commit, nothing would be collapsed because no two instruments could ever have the same program number and `is_drum`).

**Comment by craffel** [comment]
> Also relevant are instrument name and program name meta-events, as well as channel marker meta-events for type 0 MIDI files.

Incidentally, the instrument name and program name meta-events are [arguably not useful without a channel prefix meta-event](http://www.recordingblogs.com/sa/tabid/88/Default.aspx?topic=MIDI+Instrument+Name+meta+message), and as far as I can tell it's pretty common for MIDI files "in the wild" to omit the channel prefix meta-event (a sampling is copied below).  When they are present, the seem to be less than helpful (like most MIDI text events...)  So, unless someone has a major objection, I am going to only store track name meta-events for now.  This also simplifies the code somewhat.  Using the code
```Python
    for f in glob.glob('data/unique_midi/mid/1/*.mid'):
        try:
            m = midi.read_midifile(f)
        except:
            pass
        for t in m:
            cp = None
            for n, e in enumerate(t):
                if isinstance(e, midi.ChannelPrefixEvent):
                    cp = e.data[0]
                elif isinstance(e, midi.InstrumentNameEvent):
                    if cp is None:
                        print '    Got instrument name "{}" with no channel prefix'.format(e.text)
                    else:
                        print 'Got instrument name "{}" on channel {}'.format(e.text, cp)
                elif isinstance(e, midi.ProgramNameEvent):
                    if cp is None:
                        print '    Got program name "{}" with no channel prefix'.format(e.text)
                    else:
                        print 'Got program name "{}" on channel {}'.format(e.text, cp)
```

produces

```
    Got instrument name "M original  " with no channel prefix
    Got instrument name "M original  " with no channel prefix
    Got instrument name "C5P49" with no channel prefix
    Got instrument name "C11P26" with no channel prefix
    Got instrument name "C3P50" with no channel prefix
    Got instrument name "C2P36" with no channel prefix
    Got instrument name "C6P57" with no channel prefix
    Got instrument name "C4P100" with no channel prefix
    Got instrument name "C9P12" with no channel prefix
    Got instrument name "C8P53" with no channel prefix
    Got instrument name "C7P28" with no channel prefix
    Got instrument name "C12P12" with no channel prefix
    Got instrument name "gro�e Trommel 2" with no channel prefix
    Got instrument name "geschl. Hi-hat-Becken" with no channel prefix
    Got instrument name "Wirbeltrommel 1" with no channel prefix
    Got instrument name "offenes Hi-hat-Becken " with no channel prefix
    Got instrument name "mittelhohe R�hrtr. 2" with no channel prefix
    Got instrument name "tiefe R�hrtrommel 2" with no channel prefix
    Got instrument name "Becken anschlagen 1" with no channel prefix
    Got instrument name "hohe R�hrtrommel 2" with no channel prefix
    Got instrument name " aufein.schl. Becken 2" with no channel prefix
    Got instrument name "aufein.schl. Becken 1" with no channel prefix
    Got instrument name "Pedal Hi-hat-Becken" with no channel prefix
    Got instrument name "anein.schl. Becken" with no channel prefix
    Got instrument name "Main lead" with no channel prefix
    Got instrument name "melody" with no channel prefix
    Got instrument name "melody2" with no channel prefix
    Got instrument name "bassline" with no channel prefix
    Got instrument name "Young And" with no channel prefix
    Got instrument name "Foolish Again" with no channel prefix
    Got instrument name "Pgh Midi BBS" with no channel prefix
    Got instrument name "412-882-3703" with no channel prefix
    Got instrument name "oZ" with no channel prefix
Got instrument name "M Cha16 " on channel 15
Got instrument name "M Cha 1 " on channel 0
Got instrument name "M Cha15 " on channel 14
Got instrument name "M Cha14 " on channel 13
Got instrument name "M Cha 9 " on channel 8
Got instrument name "M Cha10 " on channel 9
    Got instrument name "Vocals" with no channel prefix
    Got instrument name "Guitar 1 (Acoustic)" with no channel prefix
    Got instrument name "Guitar 2 (Dist.)" with no channel prefix
    Got instrument name "Guitar 3 (Bass)" with no channel prefix
    Got instrument name "Guitar 4 (Dist.)" with no channel prefix
    Got instrument name "Guitar 5 (Dist.)" with no channel prefix
    Got instrument name "Guitar 6 (Clean)" with no channel prefix
    Got instrument name "Main Mixer 1" with no channel prefix
    Got instrument name "Percu Mixer 1" with no channel prefix
    Got instrument name "Kick" with no channel prefix
    Got instrument name "Percu 1" with no channel prefix
    Got instrument name "Lead" with no channel prefix
    Got instrument name "SubTractor 1" with no channel prefix
    Got instrument name "- WE BUILT" with no channel prefix
    Got instrument name "- THIS CITY" with no channel prefix
    Got instrument name "SubTractor 1" with no channel prefix
Got instrument name "Piano 1" on channel 0
Got instrument name "Acoustic Bs." on channel 1
Got instrument name "Steel-str Gt" on channel 2
Got instrument name "Organ 1" on channel 3
Got instrument name "Choir Aahs" on channel 4
Got instrument name "Trumpet" on channel 5
Got instrument name "Brass 1" on channel 6
Got instrument name "Harp" on channel 7
Got instrument name "Strings" on channel 8
Got instrument name "M #10" on channel 9
Got instrument name "Clarinet" on channel 10
Got instrument name "Vibraphone" on channel 11
Got instrument name "Trombone" on channel 12
Got instrument name "Tenor" on channel 13
Got instrument name "Muted Gt" on channel 14
Got instrument name "E.Piano 1" on channel 15
Got instrument name "CHA 10  " on channel 9
Got instrument name "CHA  2  " on channel 1
Got instrument name "CHA  3  " on channel 2
Got instrument name "CHA  4  " on channel 3
Got instrument name "CHA  5  " on channel 4
Got instrument name "CHA  6  " on channel 5
Got instrument name "CHA  7  " on channel 6
Got instrument name "CHA  8  " on channel 7
```

and so on.

**Comment by craffel** [comment]
Added in 414b6874261588d44c30b4ef5582c45bcdca0d7e.
