### ISSUE TITLE
Issue installing midi package on OSX

### ISSUE THREAD

**Issue by himito** [craffel/pretty-midi#66]
Hi, 

I tried to install `pretty-midi` but the `midi` dependency cannot be installed on my OSX machine. Maybe the following is the problem:
> Although OSX and Windows provide similar sequencer facilities, this API does not yet support them.

Hence, I changed  `midi` by `python-midi` in the `setup.py` file.

Jaime

**Comment by craffel** [comment]
> I tried to install pretty-midi but the midi dependency cannot be installed on my OSX machine.

I develop on an OS X machine and have installed `midi` dozens of times.  What is the error you are getting?

> >Although OSX and Windows provide similar sequencer facilities, this API does not yet support them.

This refers only to the ALSA sequencer, which `pretty_midi` does not use.  It's an optional dependency that you do not need.

> Hence, I changed midi by python-midi in the setup.py file.

This doesn't really make sense, because you're telling Python that `pretty_midi` is a requirement for `pretty_midi`.  It will result in `midi` not being installed. You can't parse MIDI files with `pretty_midi` without `midi`.

**Comment by craffel** [comment]
> > Hence, I changed midi by python-midi in the setup.py file.
> This doesn't really make sense, because you're telling Python that pretty_midi is a requirement for pretty_midi. It will result in midi not being installed. You can't parse MIDI files with pretty_midi without midi.

Looking back at this, I clearly misread you - just looked on PyPI, and indeed the correct name for the `midi` package is `python-midi`.  I feel like this may have changed at some point.  I will make a separate issue for this as it is not OSX-specific.  Thanks!
